### PR TITLE
CIV-11541 Bilingual check for notifications

### PR DESCRIPTION
**Pull request by ElifDenizEsea**
**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-11541

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by neeta-hmcts — COMMENTED** [review]
Could plz added camunda diagram here ?

**Comment by ElifDenizEsea** [comment]
camunda_bilingual

**Comment by paul-pearson** [comment]
Do we definitely want to skip the Notify RPA steps as well?

**Review by paul-pearson — COMMENTED** [review]
See general comment above

**Pull request closed without merging**
