### PR TITLE
Bug/civ 4519

### PR DESCRIPTION
**Pull request by MMNycz**
**Before creating a pull request make sure that:**

- [X] commit messages are meaningful and follow good commit message guidelines
- [X] README and other documentation has been updated / added (if needed)
- [X] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-4519

### Change description ###

Update inform_agreed_extension_date_spec_bpmn with Notify respondent 2

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by sabahirfan** [comment]
It would be a good practice to add the BPMN diagram image before and after change in description. It would be helpful while reviewing

**Comment by MMNycz** [comment]
BMPN Diagram before change:

image-2022-08-24-15-43-01-649

BPM Diagram after change:

Screenshot 2022-12-14 100348

**Review by asthamalviya — APPROVED** [review]

**Review by zikrurR — APPROVED** [review]

**Comment by sabahirfan** [comment]
Please resolve conflicts

**Comment by MMNycz** [comment]
Resolve conflicts in new PR
https://github.com/hmcts/civil-camunda-bpmn-definition/pull/465

**Pull request closed without merging**
